### ISSUE TITLE
Error message from VAMPIR using R/3.5.2

### ISSUE THREAD

**Issue by solveigmo** [hkaspersen/amr_vir_sequence_typing#4]
I get the following error-message when i try to run VAMPIR using R version 3.5.2;

Error: `.fn` must be a string, a symbol, a call, or a function
Backtrace:
     x
  1. +-base::suppressWarnings(...)
  2. | \-base::withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning"))
  3. \-`%>%`(...)
  4.   +-base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  5.   \-base::eval(quote(`_fseq`(`_lhs`)), env, env)
  6.     \-base::eval(quote(`_fseq`(`_lhs`)), env, env)
  7.       \-`_fseq`(`_lhs`)
  8.         \-magrittr::freduce(value, `_function_list`)
  9.           \-function_list[[i]](value)
 10.             \-dplyr::mutate_at(., vars(-ref), list(sub("*", "", .)))
 11.               \-dplyr:::manip_at(...)
 12.                 \-dplyr:::as_fun_list(.funs, .quo, .env, ...)
 13.                   \-dplyr:::map(.x, as_fun, .env = fun_env(.quo, .env), args)
 14.                     \-base::lapply(.x, .f
Execution halted

**Comment by hkaspersen** [comment]
Old issue, please open a new issue if problem persists with current version
